source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '13.0'

target 'Flash Chat' do
  use_frameworks!

  # Pods for Flash Chat
  pod 'CLTypingLabel', '~> 0.4.0'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  
end
